[package]
name = "sqlite1"
version = "0.1.0"
authors = ["Vincent Dagoury <vincent.dagoury@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.26.3"
